#pragma once

#include <cstdint>

namespace cat_vm {
    enum opcode : uint8_t {
        set_info,
        push_const,
        set_reg,
        push_reg,
        heap_new,
        heap_delete,
        arc_new,
        arc_hold,
        arc_drop,
        suspend,
        get_object_field,
        get_module_field,
        i8_add,
        i8_sub,
        i8_mul,
        i8_div,
        i8_rem,
        i16_add,
        i16_sub,
        i16_mul,
        i16_div,
        i16_rem,
        i32_add,
        i32_sub,
        i32_mul,
        i32_div,
        i32_rem,
        i64_add,
        i64_sub,
        i64_mul,
        i64_div,
        i64_rem,
        f32_add,
        f32_sub,
        f32_mul,
        f32_div,
        f32_rem,
        f64_add,
        f64_sub,
        f64_mul,
        f64_div,
        f64_rem,
    };
}
